baseURL = 'https://nikhilcad.github.io/'
languageCode = 'en-us'
title = 'Nikhil Site'
theme = 'papermod'

enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[minify]
disableXML = true

[permalinks]
post = "/:title/"

[languages.en]
languageName = "English"
contentDir = "content/English"
weight = 1

  [languages.en.profileMode]
  enabled = true
  title = "Nikhil Kadiyan"
  subtitle = "Welcome to my site!"

      [[languages.en.profileMode.buttons]]
      name = "About"
      url = "about"

      [[languages.en.profileMode.buttons]]
      name = "Project"
      url = "projects"

      [[languages.en.profileMode.buttons]]
      name = "Resume"
      url = "./resumeLaTeX/Nikhil_Kadiyan_Resume.pdf"

[[menu.main]]
identifier = "About"
name = "About"
url = "about"
weight = 1

[[menu.main]]
identifier = "Projects"
name = "Project"
url = "projects"
weight = 2

[[menu.main]]
identifier = "Resume"
name = "Resume"
url = "./resumeLaTeX/Nikhil_Kadiyan_Resume.pdf"
weight = 3

[[menu.main]]
identifier = "Blog"
name = "Blogs"
url = "blog"
weight = 4

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
title = "Nikhil"
author = "Nikhil"
defaultTheme = "dark"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
disableScrollToTop = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/nikhilcad"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/nikhil-kadiyan-3a044b1a0/"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:nikhilcaddilac@gmail.com"

  [params.assets]
  favicon = "k-48.png"
  favicon16x16 = "k-48.png"
  favicon32x32 = "k-48.png"
  apple_touch_icon = "k-48.png"
  safari_pinned_tab = "k-48.png"

  [params.label]
  text = "Home"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 1
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary" ]

  [params.twikoo]
  version = "1.4.11"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
