
name: Compile Latex and Release PDF  


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Nikhil_Kadiyan_Resume.tex
          latexmk_use_xelatex: true
      
      - name: Copy
        run: |
          mkdir out
          cp ./Nikhil_Kadiyan_Resume.pdf ./out/Nikhil_Kadiyan_Resume.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: Nikhil_Kadiyan_Resume
          path: out/Nikhil_Kadiyan_Resume.pdf
