name: Deploy PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Nikhil_Kadiyan_Resume.tex
          working_directory: static/resumeLaTeX/
          latexmk_use_xelatex: true
      - name: Copy
        run: |
          mkdir out
          cp ./Nikhil_Kadiyan_Resume.pdf ./out/Nikhil_Kadiyan_Resume.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: Nikhil_Kadiyan_Resume
          path: static/resumeLaTeX/Nikhil_Kadiyan_Resume.pdf