name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Nikhil_Kadiyan_Resume.tex
          working_directory: static/resumeLaTeX/
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: PDF
          path: static/resumeLaTeX/Nikhil_Kadiyan_Resume.pdf